server:
  port: 8080

spring:
  application:
    name: gateway-service

  main:
    web-application-type: REACTIVE

  profiles:
    include:
      - secret

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: user-service-public
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/login/**, /users/signup/**, /users/reissue

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
          filters:
            - name: JwtAuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: trace
    com.checkit.gatewayservice: debug