spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sample
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings