-- Checkmate PostgreSQL DDL (converted from ERD Cloud export)
-- NOTE: This script drops tables if they already exist.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
SET search_path TO public;

DROP TABLE IF EXISTS group_verification_methods CASCADE;
DROP TABLE IF EXISTS study_groups CASCADE;
DROP TABLE IF EXISTS study_group_tags CASCADE;
DROP TABLE IF EXISTS inquiry CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS notification_setting CASCADE;
DROP TABLE IF EXISTS github_verification CASCADE;
DROP TABLE IF EXISTS hashtags CASCADE;
DROP TABLE IF EXISTS exemption_requests CASCADE;
DROP TABLE IF EXISTS study_user CASCADE;
DROP TABLE IF EXISTS group_verification_frequency CASCADE;
DROP TABLE IF EXISTS checklist_verification CASCADE;
DROP TABLE IF EXISTS point_transaction CASCADE;
DROP TABLE IF EXISTS notice CASCADE;
DROP TABLE IF EXISTS gps_verification CASCADE;
DROP TABLE IF EXISTS badge_user CASCADE;
DROP TABLE IF EXISTS user_item CASCADE;
DROP TABLE IF EXISTS social_account CASCADE;
DROP TABLE IF EXISTS group_invitations CASCADE;
DROP TABLE IF EXISTS group_verification_schedule CASCADE;
DROP TABLE IF EXISTS point_product CASCADE;
DROP TABLE IF EXISTS gps_locations CASCADE;
DROP TABLE IF EXISTS badge_all CASCADE;
DROP TABLE IF EXISTS photo_verification CASCADE;
DROP TABLE IF EXISTS group_exemption CASCADE;
DROP TABLE IF EXISTS inquiry_comment CASCADE;

-- ENUMS
CREATE TYPE user_gender AS ENUM ('male', 'female');

-- TABLES
CREATE TABLE inquiry_comment (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  inquiry_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  author_type VARCHAR(10) NOT NULL,
  content TEXT NOT NULL,

  CONSTRAINT pk_inquiry_comment PRIMARY KEY (comment_id)
);

CREATE TABLE group_exemption (
    exemp_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id BIGINT NOT NULL,
    slot SMALLINT NOT NULL,
    is_enabled BOOLEAN NOT NULL,
    limit_unit VARCHAR(10) NOT NULL,
    limit_cnt INTEGER NOT NULL,
    created_at TIMESTAMPTZ,
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT chk_group_exemption_slot CHECK (slot IN (1, 2)),
    CONSTRAINT chk_group_exemption_limit_unit CHECK (limit_unit IN ('WEEK', 'MONTH', 'TOTAL')),
    CONSTRAINT uq_group_exemption_group_slot UNIQUE (group_id, slot),
    CONSTRAINT pk_group_exemption PRIMARY KEY (exemp_id)
);

CREATE TABLE photo_verification (
  photo_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  group_id BIGINT NOT NULL,
  slot SMALLINT NOT NULL,
  min_files INTEGER NOT NULL,
  max_files INTEGER NOT NULL,
  max_size INTEGER NOT NULL,
  allowed_extensions VARCHAR(100) NOT NULL,
  CONSTRAINT chk_photo_verification_slot CHECK (slot IN (1, 2)),
  CONSTRAINT uq_photo_verification_group_slot UNIQUE (group_id, slot),
  CONSTRAINT pk_photo_verification PRIMARY KEY (photo_id)
);

CREATE TABLE badge_all (
  badge_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL DEFAULT 'UNIQUE',
  description VARCHAR(255) NOT NULL,
  image_url TEXT,
  CONSTRAINT pk_badge_all PRIMARY KEY (badge_id)
);

CREATE TABLE gps_locations (
  location_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  group_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  name VARCHAR(50) NOT NULL,
  latitude DECIMAL(10,7) NOT NULL,
  longitude DECIMAL(10,7) NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT pk_gps_locations PRIMARY KEY (location_id)
);

CREATE TABLE point_product (
  product_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  price INTEGER NOT NULL,
  is_available BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT pk_point_product PRIMARY KEY (product_id)
);

CREATE TABLE group_verification_schedule (
    schedule_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id BIGINT NOT NULL,
    slot SMALLINT NOT NULL,
    end_time TIME NOT NULL,
    check_end_time TIME,
    days_of_week INTEGER NOT NULL,
    timezone VARCHAR(50) NOT NULL DEFAULT 'Asia/Seoul',
    created_at TIMESTAMPTZ,
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT chk_group_verification_schedule_slot CHECK (slot IN (1, 2)),
    CONSTRAINT uq_group_verification_schedule_group_slot UNIQUE (group_id, slot),
    CONSTRAINT pk_group_verification_schedule PRIMARY KEY (schedule_id)
);

CREATE TABLE group_invitations (
  invite_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  group_id BIGINT NOT NULL,
  invite_code VARCHAR(20) NOT NULL,
  invite_token VARCHAR(80) NOT NULL,
  expires_at TIMESTAMP,
  max_uses INTEGER,
  used_cnt INTEGER,
  revoked_at TIMESTAMP,
  CONSTRAINT uq_group_invitations_invite_code UNIQUE (invite_code),
  CONSTRAINT uq_group_invitations_invite_token UNIQUE (invite_token),
  CONSTRAINT pk_group_invitations PRIMARY KEY (invite_id)
);

CREATE TABLE social_account (
  social_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  provider VARCHAR(20) NOT NULL,
  provider_user_id VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  connected_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_social_account PRIMARY KEY (social_id)
);

CREATE TABLE user_item (
  product_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id2 UUID,
  product_id BIGINT NOT NULL,
  quantity INTEGER NOT NULL DEFAULT 1,
  CONSTRAINT pk_user_item PRIMARY KEY (product_item_id)
);

CREATE TABLE badge_user (
  badge_user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id UUID NOT NULL,
  badge_id BIGINT NOT NULL,
  name VARCHAR(20) NOT NULL,
  earned_at TIMESTAMP NOT NULL DEFAULT now(),
  is_equipped VARCHAR(255) NOT NULL DEFAULT false,
  CONSTRAINT pk_badge_user PRIMARY KEY (badge_user_id)
);

CREATE TABLE gps_verification (
  gps_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  group_id BIGINT NOT NULL,
  slot SMALLINT NOT NULL,
  radius_mode VARCHAR(12) NOT NULL,
  CONSTRAINT chk_gps_verification_slot CHECK (slot IN (1, 2)),
  CONSTRAINT chk_gps_verification_radius_mode CHECK (radius_mode IN ('COMMON', 'PER_LOCATION')),
  CONSTRAINT uq_gps_verification_group_slot UNIQUE (group_id, slot),
  CONSTRAINT pk_gps_verification PRIMARY KEY (gps_id)
);

CREATE TABLE notice (
  notice_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  view_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT pk_notice PRIMARY KEY (notice_id)
);

CREATE TABLE point_transaction (
  transaction_id UUID NOT NULL DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  type VARCHAR(10) NOT NULL,
  amount INTEGER NOT NULL,
  balance_after INTEGER NOT NULL,
  description VARCHAR(255) NOT NULL,
  CONSTRAINT chk_point_transaction_type CHECK (type IN ('전체', '적립', '환전', '사용')),
  CONSTRAINT pk_point_transaction PRIMARY KEY (transaction_id)
);

CREATE TABLE checklist_verification (
    checklist_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id BIGINT NOT NULL,
    slot SMALLINT NOT NULL,
    title VARCHAR(80) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ,
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT chk_checklist_verification_slot CHECK (slot IN (1, 2)),
    CONSTRAINT uq_checklist_verification_group_slot UNIQUE (group_id, slot),
    CONSTRAINT pk_checklist_verification PRIMARY KEY (checklist_id)
);

CREATE TABLE group_verification_frequency (
    frequency_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id BIGINT NOT NULL,
    slot SMALLINT NOT NULL,
    unit VARCHAR(10) NOT NULL,
    required_cnt INTEGER NOT NULL,
    created_at TIMESTAMPTZ,
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT chk_group_verification_frequency_slot CHECK (slot IN (1, 2)),
    CONSTRAINT chk_group_verification_frequency_unit CHECK (unit IN ('DAY', 'WEEK')),
    CONSTRAINT uq_group_verification_frequency_group_slot UNIQUE (group_id, slot),
    CONSTRAINT pk_group_verification_frequency PRIMARY KEY (frequency_id)
);

CREATE TABLE study_user (
  user_id UUID NOT NULL,
  study_id BIGINT NOT NULL,
  study_id2 BIGINT NOT NULL,
  user_id2 UUID NOT NULL,
  role VARCHAR(20) NOT NULL,
  status VARCHAR(10) NOT NULL,
  is_study_notification BOOLEAN NOT NULL DEFAULT true,
  joined_at TIMESTAMP NOT NULL DEFAULT now(),
  CONSTRAINT chk_study_user_status CHECK (status IN ('ACTIVE', 'BANNED', 'QUIT')),
  CONSTRAINT pk_study_user PRIMARY KEY (user_id, study_id)
);

CREATE TABLE exemption_requests (
  exemp_req_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  group_id BIGINT NOT NULL,
  user_id UUID NOT NULL,
  date DATE NOT NULL,
  reason VARCHAR(30),
  status VARCHAR(10) NOT NULL,
  CONSTRAINT chk_exemption_requests_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELED')),
  CONSTRAINT pk_exemption_requests PRIMARY KEY (exemp_req_id)
);

CREATE TABLE hashtags (
    hashtag_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(30) NOT NULL,
    normalized_name VARCHAR(30) NOT NULL,
    use_cnt INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ,
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT uq_hashtags_name UNIQUE (name),
    CONSTRAINT uq_hashtags_normalized_name UNIQUE (normalized_name),
    CONSTRAINT pk_hashtags PRIMARY KEY (hashtag_id)
);

CREATE TABLE github_verification (
  commit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  group_id BIGINT NOT NULL,
  repo_url VARCHAR(500) NOT NULL,
  branch VARCHAR(100) NOT NULL,
  CONSTRAINT pk_github_verification PRIMARY KEY (commit_id)
);

CREATE TABLE notification_setting (
  setting_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id UUID NOT NULL,
  is_push_enabled BOOLEAN NOT NULL DEFAULT true,
  is_night_enabled BOOLEAN NOT NULL DEFAULT true,
  CONSTRAINT pk_notification_setting PRIMARY KEY (setting_id)
);

CREATE TABLE users (
  user_id UUID NOT NULL DEFAULT gen_random_uuid(),
  email VARCHAR(255) NOT NULL,
  name VARCHAR(50) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  nickname VARCHAR(50) NOT NULL,
  gender user_gender,
  birthdate DATE,
  phone_number VARCHAR(20),
  is_active BOOLEAN NOT NULL DEFAULT true,
  fav_category_1 VARCHAR(10),
  fav_category_2 VARCHAR(10),
  fav_category_3 VARCHAR(10),
  profile_image_url VARCHAR(500),
  CONSTRAINT chk_users_fav_category_1 CHECK (fav_category_1 IN ('WAKE', 'SEATED', 'COTE', 'LANG', 'CERT', 'ETC')),
  CONSTRAINT chk_users_fav_category_2 CHECK (fav_category_2 IN ('WAKE', 'SEATED', 'COTE', 'LANG', 'CERT', 'ETC')),
  CONSTRAINT chk_users_fav_category_3 CHECK (fav_category_3 IN ('WAKE', 'SEATED', 'COTE', 'LANG', 'CERT', 'ETC')),
  CONSTRAINT uq_users_email UNIQUE (email),
  CONSTRAINT uq_users_nickname UNIQUE (nickname),
  CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE inquiry (
  inquiry_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id UUID NOT NULL,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  status VARCHAR(20) NOT NULL,
  CONSTRAINT pk_inquiry PRIMARY KEY (inquiry_id)
);

CREATE TABLE study_group_tags (
    mapping_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id BIGINT NOT NULL,
    hashtag_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ,
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT uq_study_group_tags_group_hashtag UNIQUE (group_id, hashtag_id),
    CONSTRAINT pk_study_group_tags PRIMARY KEY (mapping_id)
);

CREATE TABLE study_groups (
    group_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    min_members INTEGER NOT NULL,
    max_members INTEGER NOT NULL,
    current_members INTEGER NOT NULL,
    status VARCHAR(10) NOT NULL,
    owner_user_id UUID NOT NULL,
    thumbnail_type VARCHAR(10) NOT NULL,
    thumbnail_url VARCHAR(500),
    category VARCHAR(10) NOT NULL,
    join_type VARCHAR(11) NOT NULL,
    start_date DATE,
    end_date DATE,
    duration_weeks INTEGER,
    is_indefinite BOOLEAN,
    closed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT chk_study_groups_status CHECK (status IN ('RECRUITING', 'CLOSED')),
    CONSTRAINT chk_study_groups_thumbnail_type CHECK (thumbnail_type IN ('UPLOAD', 'DEFAULT')),
    CONSTRAINT chk_study_groups_category CHECK (category IN ('WAKE', 'SEATED', 'COTE', 'LANG', 'CERT', 'ETC')),
    CONSTRAINT chk_study_groups_join_type CHECK (join_type IN ('PUBLIC', 'INVITE_ONLY')),
    CONSTRAINT pk_study_groups PRIMARY KEY (group_id)
);

CREATE TABLE group_verification_methods (
    method_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    group_id BIGINT NOT NULL,
    slot SMALLINT NOT NULL,
    method_code VARCHAR(10) NOT NULL,
    details_json TEXT,
    created_at TIMESTAMPTZ,
    created_by UUID,
    updated_at TIMESTAMPTZ,
    updated_by UUID,
    deleted_at TIMESTAMPTZ,
    deleted_by UUID,
    CONSTRAINT chk_group_verification_methods_slot CHECK (slot IN (1, 2)),
    CONSTRAINT chk_group_verification_methods_method_code CHECK (method_code IN ('PHOTO', 'CHECKLIST', 'GPS', 'GITHUB')),
    CONSTRAINT uq_group_verification_methods_group_slot UNIQUE (group_id, slot),
    CONSTRAINT pk_group_verification_methods PRIMARY KEY (method_id)
);

-- Column comments
COMMENT ON COLUMN inquiry_comment.author_type IS 'ADMIN, USER';
COMMENT ON COLUMN group_exemption.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN group_exemption.limit_unit IS 'WEEK / MONTH / TOTAL';
COMMENT ON COLUMN photo_verification.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN photo_verification.slot IS '인증 규칙 슬롯(1 또는 2)';
COMMENT ON COLUMN photo_verification.max_size IS 'MB';
COMMENT ON COLUMN badge_all.badge_id IS '뱃지 고유 ID';
COMMENT ON COLUMN badge_all.name IS '뱃지 이름';
COMMENT ON COLUMN badge_all.description IS '뱃지 설명';
COMMENT ON COLUMN badge_all.image_url IS '뱃지 이미지';
COMMENT ON COLUMN gps_locations.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN gps_locations.name IS '집, 도서관 등';
COMMENT ON COLUMN point_product.product_id IS '상품 고유 ID';
COMMENT ON COLUMN point_product.name IS '상품이름';
COMMENT ON COLUMN point_product.category IS 'TODO, 코테, all';
COMMENT ON COLUMN point_product.price IS '상품가격';
COMMENT ON COLUMN point_product.is_available IS '현재 구매 가능 여부';
COMMENT ON COLUMN group_verification_schedule.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN group_verification_schedule.end_time IS '인증 종료 시간';
COMMENT ON COLUMN group_verification_schedule.check_end_time IS '체크인증 완료 시간';
COMMENT ON COLUMN group_verification_schedule.days_of_week IS '비트마스크';
COMMENT ON COLUMN group_invitations.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN group_invitations.invite_code IS 'UNIQUE';
COMMENT ON COLUMN group_invitations.invite_token IS 'UNIQUE';
COMMENT ON COLUMN social_account.social_id IS '소설 연동 ID';
COMMENT ON COLUMN social_account.provider IS 'KAKAO, GOOGLE, GITHUB';
COMMENT ON COLUMN social_account.provider_user_id IS '소셜 서버에 주는 고유 번호';
COMMENT ON COLUMN social_account.email IS '연동된 소셜 서버 이메일';
COMMENT ON COLUMN social_account.connected_at IS '연동 일시';
COMMENT ON COLUMN user_item.product_item_id IS '보유 내역 고유 ID';
COMMENT ON COLUMN user_item.product_id IS '상품 고유 ID';
COMMENT ON COLUMN badge_user.badge_user_id IS '고유한 나의 뱃지 번호';
COMMENT ON COLUMN badge_user.badge_id IS '뱃지 고유 ID';
COMMENT ON COLUMN badge_user.earned_at IS '획득일시';
COMMENT ON COLUMN badge_user.is_equipped IS '대표 뱃지 1개 설정가능';
COMMENT ON COLUMN gps_verification.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN gps_verification.slot IS '인증 규칙 슬롯(1 또는 2)';
COMMENT ON COLUMN gps_verification.radius_mode IS 'COMMON / PER_LOCATION';
COMMENT ON COLUMN point_transaction.transaction_id IS '포인트 내역 고유ID';
COMMENT ON COLUMN point_transaction.type IS '전체/적립/환전/사용';
COMMENT ON COLUMN point_transaction.description IS '적립사유, 면제권 구매';
COMMENT ON COLUMN checklist_verification.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN group_verification_frequency.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN group_verification_frequency.unit IS 'DAY / WEEK';
COMMENT ON COLUMN study_user.study_id IS '고유 스터디 ID';
COMMENT ON COLUMN study_user.study_id2 IS '고유 스터디 ID';
COMMENT ON COLUMN study_user.role IS 'Leader, Member';
COMMENT ON COLUMN study_user.status IS 'ACTIVE, BANNED, QUIT';
COMMENT ON COLUMN exemption_requests.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN exemption_requests.date IS '면제 적용 날짜';
COMMENT ON COLUMN exemption_requests.status IS 'PENDING / APPROVED / REJECTED / CANCELED';
COMMENT ON COLUMN hashtags.name IS 'UNIQUE';
COMMENT ON COLUMN hashtags.normalized_name IS '검색용 정규화(소문자/공백제거 등)';
COMMENT ON COLUMN hashtags.use_cnt IS '자동완성 정렬용';
COMMENT ON COLUMN github_verification.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN notification_setting.is_push_enabled IS '전체 푸시 알림 여부';
COMMENT ON COLUMN notification_setting.is_night_enabled IS '야간(22 ~ 07) 알림 여부';
COMMENT ON COLUMN users.email IS 'UNIQUE';
COMMENT ON COLUMN users.nickname IS 'UNIQUE';
COMMENT ON COLUMN users.fav_category_1 IS 'WAKE / SEATED / COTE / LANG / CERT / ETC';
COMMENT ON COLUMN users.fav_category_2 IS 'WAKE / SEATED / COTE / LANG / CERT / ETC';
COMMENT ON COLUMN users.fav_category_3 IS 'WAKE / SEATED / COTE / LANG / CERT / ETC';
COMMENT ON COLUMN study_group_tags.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN study_groups.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN study_groups.title IS '그룹명';
COMMENT ON COLUMN study_groups.description IS '스터디 소개글';
COMMENT ON COLUMN study_groups.max_members IS '정원';
COMMENT ON COLUMN study_groups.current_members IS '현재 참여 인원';
COMMENT ON COLUMN study_groups.status IS 'RECRUITING / CLOSED';
COMMENT ON COLUMN study_groups.owner_user_id IS '그룹장 ID';
COMMENT ON COLUMN study_groups.thumbnail_type IS 'UPLOAD, DEFAULT';
COMMENT ON COLUMN study_groups.thumbnail_url IS '업로드 썸네일 URL';
COMMENT ON COLUMN study_groups.category IS 'WAKE / SEATED / COTE / LANG / CERT / ETC';
COMMENT ON COLUMN study_groups.join_type IS 'PUBLIC / INVITE_ONLY';
COMMENT ON COLUMN study_groups.duration_weeks IS 'n주 기간';
COMMENT ON COLUMN group_verification_methods.group_id IS '고유 스터디 ID';
COMMENT ON COLUMN group_verification_methods.method_code IS 'PHOTO / CHECKLIST / GPS / GITHUB';

COMMIT;